name: Build and Deploy

env:
  SITE_FOLDER: "."
  CLEAR_CACHE: ${{ contains(github.event.head_commit.message, '[clear]') }}

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
                docs/__cache
                ~/.julia/artifacts
                ~/.julia/packages
                ~/.cache/pip
          key: ${{ runner.os }}-franklin-cache-${{ github.sha }}
          restore-keys: ${{ runner.os }}-franklin-cache-

      # Julia
      - name: Install Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: 1.7

      # Python3
      - run: pip install matplotlib

      # Website build
      - run: julia -e '
                using Pkg;
                Pkg.add(url="https://github.com/tlienart/Xranklin.jl", rev="main");
                using Xranklin;
                build("${{ env.SITE_FOLDER }}"; clear=${{ env.CLEAR_CACHE }});'

      # Deployment and caching
      - run: touch ${{ env.SITE_FOLDER }}/__site/.nojekyll
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          BRANCH: gh-pages
          FOLDER: ${{ env.SITE_FOLDER }}/__site
